### ISSUE TITLE
stringi dependency

### ISSUE THREAD

**Issue by johnyaku** [PYangLab/PhosR#3]
Hi guys, nice work :)
Looks like PhosR also requires stringi?
I had to install stringi to get it to load anyway...
Perhaps you could add stringi to your "imports" list :)

**Comment by HaniJieunKim** [comment]
Hi @johnyaku 

Thank you for the suggestion! The dependency has been added [here](https://github.com/PYangLab/PhosR/commit/16e8847000177e84206fef01265ff6162f69158c).
