### ISSUE TITLE
PDF format heatmap from kinaseSubstrateHeatmap function.

### ISSUE THREAD

**Issue by IgnatiusPang** [PYangLab/PhosR#4]
I have tried to capture the heatmap from kinaseSubstrateHeatmap function but it did not work for me in the iPython notebook. Would it be possible to add in the function the option to input a file name (with PDF or JPG suffix) that will be passed onto the pheatmap function when I want the heatmap saved in a file? Currently, the heatmap is only printed onto the notebook in my iPython/Jupyter notebook.

**Comment by HaniJieunKim** [comment]
Hi Iggy,

Apologies for the delay. We have updated the kinaseSubstrateHeatmap so that the user can specify the filename wherein the image can be saved.

Please see our update[ here](https://github.com/PYangLab/PhosR/commit/d2cb6f91590fcd6047d2eaf1c5817a751006215b).

Many thanks,
Hani
