### ISSUE TITLE
Outdated version on bioconductor / bioconda

### ISSUE THREAD

**Issue by acesnik** [PYangLab/PhosR#6]
Hi there,

Thanks for the hard work on this package. I'm having success getting it to work, and the documentation is quite good!

I'm wondering a bit about the versioning. It looks like the latest version is 1.5.1 based on your documentation, but the latest on bioconductor and bioconda is 1.4.0. Is there another place I should pull this library from to get the most up-to-date version?

Anthony

**Comment by acesnik** [comment]
I've also noticed that some dependencies don't come along with the `bioconda` distribution, e.g. `r-directPA`, which might be outside your domain, but I figured I'd mention it.

**Comment by HaniJieunKim** [comment]
Thanks @acesnik. Apologies for the late response. We are continually updating our package, therefore the latest version will be on github.

**Comment by HaniJieunKim** [comment]
Yes, directPA is not included in bioconductor.
