### ISSUE TITLE
NAs lead to cryptic errors in kinase substrate scoring and downstream functions

### ISSUE THREAD

**Issue by IwanParf** [PYangLab/PhosR#8]
Hello,
The entire workflow including missing value imputation is fine as it is, but if one starts from the kinase substrate scoring step one faces issues with missing values that lead to cryptic error messages (subscript out of bounds or sth similar). Depending on the input the kinase substrate scoring might work generating the heatmap but then the kinase substrate prediction fails  with a subscript out of bounds error. After I realized that, it was of course an easy fix. Nonetheless, It would be nice to include a line where the scoring function checks for missing values and produces a meaningful error or filters those out automatically. Of note, the standardise function on P sites with at least one missing value propagates to the entire P site becoming NA across all samples, which of course aggravates the problem.

Best,

Iwan

**Comment by HaniJieunKim** [comment]
Thanks @IwanParf for the suggestion. I'll look into this.

**Comment by HaniJieunKim** [comment]
Hi @IwanParf 

Thanks for the suggestion. I have added an error message when NAs are detected in the quantification matrix for the kinaseSubstrateScore function.

Please see the changes [here](https://github.com/PYangLab/PhosR/commit/16e8847000177e84206fef01265ff6162f69158c).

Many thanks,

Hani
